### ISSUE TITLE
merge/unmerge needs to specify a response in the example/model

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/global-api#8]
POST /clients/{clientId}/dedup/merge and POST /clients/{clientId}/dedup/unmerge

![image](https://user-images.githubusercontent.com/4115079/64490794-c2339600-d22e-11e9-94b5-8206fda6a9e3.png)

**Comment by logicsandeep** [comment]
Added documentation example for merge/unmger.
https://api.hslynk.com/#/default/POST_clients-clientId-dedup-unmerge

**Comment by logicsandeep** [comment]
c628e98e669ce44f9af71108cd33718415aa9038
